name: FrontBack Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  Build-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install --legacy-peer-deps
        working-directory: ./Frontend

      - run: CI=false npm run build
        working-directory: ./Frontend

      - run: |
          aws s3 cp --recursive ./Frontend/build s3://netflix1-react --region ap-northeast-2
          if [ $? -ne 0 ]; then exit 1; fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Build-Backend:
    name: Build & Deploy Spring Boot EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix ./backend/netflix2/gradlew
          chmod +x ./backend/netflix2/gradlew

      - run: ./gradlew build -x test
        working-directory: ./backend/netflix2

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=i-01407f869499ddfe1" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Spring Boot JAR" \
            --parameters 'commands=[
              "sudo cp /tmp/netflix2-0.0.1-SNAPSHOT.jar /home/ubuntu/app.jar",
              "sudo chown ubuntu:ubuntu /home/ubuntu/app.jar",
              "sudo systemctl daemon-reload",
              "sudo systemctl stop myapp || true",
              "sudo systemctl start myapp"
            ]' \
            --region ap-northeast-2
